server.servlet.context-path=/yourapp
server.tomcat.additional-tld-skip-patterns=htmlunit-*.jar,jetty-*.jar

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=10000

# To use a different database, comment out the HSQLDB url and driver-class-name
# below and uncomment the corresponding one. If you don't find yours,
# look on the internet for the JDBC URL and driver class for your database and
# define your own entries.
#
# You have to adapt the URL to match your server, and maybe the port.
# You have to define the correct user name and password for your database above.
#
# Moreover, you have to add the JDBC driver (a jar file) corresponding to your
# database to your project dependencies (pom.xml).

# HSQLDB
spring.datasource.url=jdbc:hsqldb:hsql://localhost:1666
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver

# MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost/
#spring.datasource.driver-class-name=org.postgresql.Driver

# Oracle
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# AS/400
#spring.datasource.url=jdbc:as400:localhost
#spring.datasource.driver-class-name=com.ibm.as400.access.AS400JDBCDriver
