

// File generated by OpenXava: Fri Feb 04 12:23:41 CET 2022
// Archivo generado por OpenXava: Fri Feb 04 12:23:41 CET 2022

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: CustomerGroup		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ICustomerGroup  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_name = "name"; 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException; 	
	public static final String PROPERTY_id = "id"; 	
	String getId() throws RemoteException;		

	// References/Referencias

	// Methods 


}