

// File generated by OpenXava: Thu Jul 23 20:22:33 CEST 2020
// Archivo generado por OpenXava: Thu Jul 23 20:22:33 CEST 2020

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: OneLineAddress		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IOneLineAddress  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_fullAddress = "fullAddress"; 
	String getFullAddress() throws RemoteException;
	void setFullAddress(String fullAddress) throws RemoteException;		

	// References/Referencias

	// Methods 


}