

// File generated by OpenXava: Fri Mar 22 11:39:02 CET 2019
// Archivo generado por OpenXava: Fri Mar 22 11:39:02 CET 2019

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: SelectSchema		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ISelectSchema  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_schema = "schema"; 
	int getSchema() throws RemoteException;
	void setSchema(int schema) throws RemoteException;		

	// References/Referencias

	// Methods 


}