server.servlet.context-path=/openxavatest
server.tomcat.additional-tld-skip-patterns=htmlunit-*.jar,jetty-*.jar

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=10000

# HSQLDB
spring.datasource.url=jdbc:hsqldb:hsql://localhost:1666
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver

# Additional datasources (secondary persistence units in persistence.xml)
openxava.datasources.companya.jndi=jdbc/companyaDS
openxava.datasources.companya.url=jdbc:hsqldb:file:data/company-a-db
openxava.datasources.companya.username=sa
openxava.datasources.companya.password=
openxava.datasources.companya.driver-class-name=org.hsqldb.jdbcDriver
openxava.datasources.companya.maximum-pool-size=20
openxava.datasources.companya.minimum-idle=5
openxava.datasources.companya.connection-timeout=10000

openxava.datasources.companyb.jndi=jdbc/companybDS
openxava.datasources.companyb.url=jdbc:hsqldb:file:data/company-b-db
openxava.datasources.companyb.username=sa
openxava.datasources.companyb.password=
openxava.datasources.companyb.driver-class-name=org.hsqldb.jdbcDriver
openxava.datasources.companyb.maximum-pool-size=20
openxava.datasources.companyb.minimum-idle=5
openxava.datasources.companyb.connection-timeout=10000
