server.servlet.context-path=/openxavatest
server.tomcat.additional-tld-skip-patterns=htmlunit-*.jar,jetty-*.jar

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=10000

# HSQLDB
spring.datasource.url=jdbc:hsqldb:hsql://localhost:1666
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver
