package org.openxava.annotations;

import java.lang.annotation.*;

import org.openxava.filters.VoidFilter;

/**
 * Restricts the elements that appear in the collection. <p>
 * 
 * Applies to collections.<p>
 * 
 * You have full freedom to define how the collection data is obtained, 
 * with condition you can overwrite the default condition generated by OpenXava:
 * <pre>
 * &nbsp;@Condition(
 * &nbsp;&nbsp;&nbsp;"${warehouse.zoneNumber} = ${this.warehouse.zoneNumber} AND " + 
 * &nbsp;&nbsp;&nbsp;"${warehouse.number} = ${this.warehouse.number} AND " +
 * &nbsp;&nbsp;&nbsp;"NOT (${number} = ${this.number})"
 * &nbsp;)
 * </pre>
 * If you have this collection within Carrier, you can obtain with this collection 
 * all carriers of the same warehouse but not himself, that is the list of his 
 * fellow workers. As you see you can use this in the condition in order to 
 * reference the value of a property of current object.
 * 
 * @author Javier Paniza
 */

@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.METHOD })
public @interface Condition {
	String value();
	
	/**
	 * Allows to define programmatically some logic to apply to the values
	 * entered by user when he filters the collection data.
	 * 
	 * @since 7.7
	 */
	Class filter() default VoidFilter.class;
}
