/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2019-08-21 08:32:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava.editors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.Collection;
import java.util.Map;
import org.openxava.controller.meta.MetaAction;
import org.openxava.web.Ids;
import org.openxava.controller.meta.MetaControllers;
import org.openxava.util.Is;
import org.openxava.util.Maps;
import org.openxava.web.Actions;
import org.openxava.util.XavaPreferences;
import org.openxava.view.View;
import org.openxava.model.meta.MetaProperty;
import org.openxava.model.meta.MetaReference;
import org.openxava.web.DescriptionsLists;
import org.openxava.web.WebEditors;

public final class elementCollectionEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/standard-jstlel.jar", Long.valueOf(1566305477209L));
    _jspx_dependants.put("jar:file:/C:/Users/javi/git/openxava/OpenXavaTest/web/WEB-INF/lib/standard-jstlel.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1425975068000L));
    _jspx_dependants.put("jar:file:/C:/Users/javi/git/openxava/OpenXavaTest/web/WEB-INF/lib/standard-jstlel.jar!/META-INF/c-1_0.tld", Long.valueOf(1425975068000L));
    _jspx_dependants.put("/xava/editors/../imports.jsp", Long.valueOf(1566305476832L));
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1566305477213L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.openxava.model.meta.MetaProperty");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.openxava.util.XavaPreferences");
    _jspx_imports_classes.add("org.openxava.web.DescriptionsLists");
    _jspx_imports_classes.add("org.openxava.model.meta.MetaReference");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("org.openxava.web.Ids");
    _jspx_imports_classes.add("org.openxava.util.Is");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaAction");
    _jspx_imports_classes.add("org.openxava.web.Actions");
    _jspx_imports_classes.add("org.openxava.util.Maps");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.openxava.view.View");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaControllers");
    _jspx_imports_classes.add("org.openxava.web.WebEditors");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005freadOnlyAsLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005feditor_0026_005fthrowPropertyChanged_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005freadOnlyAsLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005feditor_0026_005fthrowPropertyChanged_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005freadOnlyAsLabel_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005feditor_0026_005fthrowPropertyChanged_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      org.openxava.controller.ModuleContext context = null;
      synchronized (session) {
        context = (org.openxava.controller.ModuleContext) _jspx_page_context.getAttribute("context", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (context == null){
          context = new org.openxava.controller.ModuleContext();
          _jspx_page_context.setAttribute("context", context, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      org.openxava.util.Messages errors = null;
      errors = (org.openxava.util.Messages) _jspx_page_context.getAttribute("errors", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (errors == null){
        errors = new org.openxava.util.Messages();
        _jspx_page_context.setAttribute("errors", errors, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.openxava.web.style.Style style = null;
      style = (org.openxava.web.style.Style) _jspx_page_context.getAttribute("style", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (style == null){
        style = new org.openxava.web.style.Style();
        _jspx_page_context.setAttribute("style", style, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write('\n');

String collectionName = request.getParameter("collectionName");
String viewObject = request.getParameter("viewObject");
String viewName = viewObject + "_" + collectionName;
View view = (View) context.get(request, viewObject);
View subview = view.getSubview(collectionName);
String idCollection = org.openxava.web.Collections.id(request, collectionName);
String propertyPrefixAccumulated = request.getParameter("propertyPrefix");
String propertyPrefix = propertyPrefixAccumulated == null?collectionName + ".":propertyPrefixAccumulated + collectionName + ".";

String rowStyle = "border-bottom: 1px solid;";
boolean resizeColumns = style.allowsResizeColumns() && XavaPreferences.getInstance().isResizeColumns();
String browser = request.getHeader("user-agent");
boolean scrollSupported = !(browser != null && (browser.indexOf("MSIE 6") >= 0 || browser.indexOf("MSIE 7") >= 0));
String styleOverflow = org.openxava.web.Lists.getOverflow(browser, subview.getMetaPropertiesList());
String collectionClass = subview.isEditable()?"class='" + style.getElementCollection() + "'":"";
boolean sortable = subview.isCollectionSortable();
String removeSelectedAction = subview.getRemoveSelectedCollectionElementsAction();
boolean suppressRemoveAction = removeSelectedAction != null && "".equals(removeSelectedAction);

      out.write("\n");
      out.write("<div ");
      out.print(collectionClass);
      out.write('>');
      out.write('\n');
 if (resizeColumns && scrollSupported) { 
      out.write(" \n");
      out.write("<div class=\"");
      if (_jspx_meth_xava_005fid_005f0(_jspx_page_context))
        return;
      out.write("\" style=\"");
      out.print(styleOverflow);
      out.write('"');
      out.write('>');
      out.write('\n');
 } 
      out.write("\n");
      out.write("<table id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f1 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f1_reused = false;
      try {
        _jspx_th_xava_005fid_005f1.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f1.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(47,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fid_005f1.setName(idCollection);
        int _jspx_eval_xava_005fid_005f1 = _jspx_th_xava_005fid_005f1.doStartTag();
        if (_jspx_th_xava_005fid_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f1);
        _jspx_th_xava_005fid_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f1_reused);
      }
      out.write("\" class=\"");
      out.print(style.getList());
      out.write('"');
      out.write(' ');
      out.print(style.getListCellSpacing());
      out.write(" style=\"");
      out.print(style.getListStyle());
      out.write('"');
      out.write('>');
      out.write('\n');
 if (sortable) { 
      out.write("<tbody class=\"xava_sortable_elements\">");
 } 
      out.write(" \n");
      out.write("<tr class=\"");
      out.print(style.getListHeader());
      out.write("\">\n");
      out.write("\t");
 if (subview.isCollectionEditable()) { 
      out.write("\n");
      out.write("\t<th class=");
      out.print(style.getListHeaderCell());
      out.write(" width=\"5\"/>\n");
      out.write("\t");
 } 
      out.write('\n');

	// Heading
Iterator it = subview.getMetaPropertiesList().iterator();
for (int columnIndex=0; it.hasNext(); columnIndex++) {
	MetaProperty p = (MetaProperty) it.next();	
	String label = p.getQualifiedLabel(request);
	int columnWidth = subview.getCollectionColumnWidth(columnIndex);
	String width = columnWidth<0 || !resizeColumns?"":"width: " + columnWidth + "px";
	MetaReference ref = null;	
	if (p.getName().contains(".")) {
		String refName = org.openxava.util.Strings.noLastTokenWithoutLastDelim(p.getName(), ".");
		ref = subview.getMetaReference(refName);
	}
	String headerId = "";
	String dataDefaultValue = "";	
	if (p.hasNotDependentDefaultValueCalculator() || ref != null && ref.hasNotDependentDefaultValueCalculator()) { 	
		Object defaultValue = null; 
		String propertyId = null;
		if (ref != null && subview.displayAsDescriptionsList(ref) && ref.getMetaModelReferenced().getAllKeyPropertiesNames().size() > 1) {
			java.util.Map refValues = subview.getSubview(ref.getName()).getValues();  
			defaultValue = p.getMetaModel().toString(refValues);
			propertyId = ref.getName() + DescriptionsLists.COMPOSITE_KEY_SUFFIX;
		}
		else {
			if (ref != null && subview.displayAsDescriptionsList(ref) && !p.isKey()) {
				MetaProperty key = (MetaProperty) p.getMetaModel().getMetaPropertiesKey().iterator().next();
				p = key.cloneMetaProperty();
				p.setName(ref.getName() + "." + key.getName());
			}		
			if (org.openxava.web.WebEditors.mustToFormat(p, subview.getViewName())) {				
				Object value = subview.getDefaultValueInElementCollection(p.getName());
				defaultValue = value==null?null:org.openxava.web.WebEditors.formatToStringOrArray(request, p, value, errors, subview.getViewName(), false); 
				propertyId = p.getName();
			}		
		}
		if (defaultValue instanceof String) { // We don't support arrays by now
			dataDefaultValue = "data-default-value='" + defaultValue + "'";
			String id = Ids.decorate(request, collectionName + ".H." + propertyId);			
			headerId = "id='" + id + "'";
		}
	}

      out.write("\n");
      out.write("\t<th ");
      out.print(headerId);
      out.write(' ');
      out.print(dataDefaultValue);
      out.write(" class=");
      out.print(style.getListHeaderCell());
      out.write(" style=\"padding-right: 0px\">\n");
      out.write("\t\t<div id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f2 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f2_reused = false;
      try {
        _jspx_th_xava_005fid_005f2.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f2.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(96,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fid_005f2.setName(idCollection);
        int _jspx_eval_xava_005fid_005f2 = _jspx_th_xava_005fid_005f2.doStartTag();
        if (_jspx_th_xava_005fid_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f2);
        _jspx_th_xava_005fid_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f2, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f2_reused);
      }
      out.write("_col");
      out.print(columnIndex);
      out.write("\" class=\"");
      out.print(((resizeColumns)?("xava_resizable"):("")));
      out.write("\" style=\"overflow: hidden; ");
      out.print(width);
      out.write("\" >\n");
      out.write("\t\t");
if (resizeColumns) {
      out.write("<nobr>");
}
      out.write('\n');
      out.write('	');
      out.write('	');
      out.print(label);
      out.write("&nbsp;\n");
      out.write("\t\t");
if (resizeColumns) {
      out.write("</nobr>");
}
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</th>\n");
      out.write("\t");
 if (ref != null && subview.isSearchForReference(ref) && subview.isLastSearchKey(p.getName())) { 
      out.write("\n");
      out.write("\t<th></th>\n");
      out.write("\t");
 } 
      out.write('\n');

	}

      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");

	// Values
Collection values = subview.getCollectionValues();
if (values == null) values = java.util.Collections.EMPTY_LIST;
int rowCount = subview.isCollectionEditable()?values.size() + 2:values.size(); 
for (int f=0; f < rowCount; f++) {
	String cssClass=f%2==0?style.getListPair():style.getListOdd();
	String cssCellClass=f%2==0?style.getListPairCell():style.getListOddCell();
	String idRow = Ids.decorate(request, propertyPrefix) + f;	
	String events=f%2==0?style.getListPairEvents():style.getListOddEvents();
	String newRowStyle = subview.isCollectionEditable() && f == rowCount - 1?"display: none;":"";
	String lastRowEvent = subview.isCollectionEditable() && f >= rowCount - 2?"onchange='elementCollectionEditor.onChangeRow(this, "+  f + ")'":"";
	String actionsStyle = subview.isCollectionEditable() && f >= rowCount - 2?"style='visibility:hidden;'":"";
	String app = request.getParameter("application");
	String module = request.getParameter("module");
	boolean hasTotals = subview.hasCollectionTotals();
	String sortableClass = subview.isCollectionEditable() && f >= rowCount - 2?"":"xava_sortable_element_row";

      out.write("\n");
      out.write("<tr id=\"");
      out.print(idRow);
      out.write("\" class=\"");
      out.print(cssClass);
      out.write(' ');
      out.print(sortableClass);
      out.write('"');
      out.write(' ');
      out.print(events);
      out.write(" style=\"border-bottom: 1px solid; ");
      out.print(newRowStyle);
      out.write('"');
      out.write('>');
      out.write('\n');
 if (subview.isCollectionEditable()) { 
      out.write("\n");
      out.write("\t<td class=\"");
      out.print(cssCellClass);
      out.write("\" style=\"vertical-align: middle;text-align: center;padding-right: 2px; ");
      out.print(style.getListCellStyle());
      out.write("\">\n");
      out.write("\t<nobr ");
      out.print(actionsStyle);
      out.write('>');
      out.write('\n');
      out.write('	');
if (sortable) { 
      out.write("\n");
      out.write("\t<i class=\"xava_handle mdi mdi-swap-vertical\"></i>\n");
      out.write("\t");
}
      out.write('\n');
      out.write('	');
if (!Is.emptyString(removeSelectedAction)) {
      out.write('\n');
      out.write('	');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f0 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      boolean _jspx_th_xava_005faction_005f0_reused = false;
      try {
        _jspx_th_xava_005faction_005f0.setPageContext(_jspx_page_context);
        _jspx_th_xava_005faction_005f0.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(136,1) name = action type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005faction_005f0.setAction(removeSelectedAction);
        // /xava/editors/elementCollectionEditor.jsp(136,1) name = argv type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005faction_005f0.setArgv("row=" + f + ",viewObject=" + viewName);
        int _jspx_eval_xava_005faction_005f0 = _jspx_th_xava_005faction_005f0.doStartTag();
        if (_jspx_th_xava_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f0);
        _jspx_th_xava_005faction_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005faction_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005faction_005f0_reused);
      }
      out.write('\n');
      out.write('	');
} else if (suppressRemoveAction){
      out.write("\n");
      out.write("\t <a title='");
      if (_jspx_meth_xava_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("' href=\"javascript:void(0)\">\n");
      out.write("\t\t<img \t\t \n");
      out.write("\t\t\tsrc='");
      out.print(request.getContextPath());
      out.write("/xava/images/spacer.gif'\n");
      out.write("\t\t\tborder='0' align='absmiddle'/>\n");
      out.write("\t </a>\n");
      out.write("\t");
} else { 
      out.write("\n");
      out.write("\t <a title='");
      if (_jspx_meth_xava_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("' href=\"javascript:void(0)\" class='");
      out.print(style.getActionImage());
      out.write("'>\n");
      out.write("\t \t");
 String onclick="elementCollectionEditor.removeRow('" + app + "', '" + module + "', this, " + f + ", " + hasTotals + ")"; 
      out.write("\n");
      out.write("\t \t");
 if (style.isUseIconsInsteadOfImages()) { 
      out.write("\n");
      out.write("\t\t<i class=\"mdi mdi-delete\" onclick=\"");
      out.print(onclick);
      out.write("\"></i>\n");
      out.write("\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t<img \t\t \n");
      out.write("\t\t\tsrc='");
      out.print(request.getContextPath());
      out.write("/xava/images/delete.gif'\n");
      out.write("\t\t\tborder='0' align='absmiddle' onclick=\"");
      out.print(onclick);
      out.write("\"/>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t </a>\n");
      out.write("\t");
} 
      out.write("\t\n");
      out.write("\t</nobr>\n");
      out.write("\t</td>\n");
 } 
      out.write('\n');

	it = subview.getMetaPropertiesList().iterator();	
	for (int columnIndex = 0; it.hasNext(); columnIndex++) { 
		MetaProperty p = (MetaProperty) it.next();
		String align =p.isNumber() && !p.hasValidValues()?"vertical-align: middle;text-align: right; ":"vertical-align: middle; "; 
		String cellStyle = style.getListCellStyle() + align; 
		int columnWidth = subview.getCollectionColumnWidth(columnIndex);
		String width = columnWidth<0 || !resizeColumns?"":"width: " + columnWidth + "px";
		String referenceName = null;
		String searchAction = null;
		if (p.getName().contains(".")) {
			String refName = org.openxava.util.Strings.noLastTokenWithoutLastDelim(p.getName(), ".");
			if (subview.displayAsDescriptionsList(subview.getMetaReference(refName))) {
				referenceName = collectionName + "." + f + "." + refName;
			}
			else { 			
				View refView = subview.getSubview(refName);
				if (refView.isSearch()) searchAction = refView.getSearchAction();
			}
		}
		String propertyName = collectionName + "." + f + "." + p.getName();
		boolean throwPropertyChanged = subview.throwsPropertyChanged(p.getName());
		Object fvalue = null;
		if (!subview.isCollectionMembersEditables()) {
			Object value = view.getValue(propertyName); 
			fvalue = org.openxava.web.WebEditors.formatToStringOrArray(request, p, value, errors, view.getViewName(), false);
		}

      out.write("\n");
      out.write("\t<td class=\"");
      out.print(cssCellClass);
      out.write(' ');
      out.print(style.getElementCollectionDataCell());
      out.write("\" style=\"");
      out.print(cellStyle);
      out.write("; padding-right: 0px\">\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f3 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f3_reused = false;
      try {
        _jspx_th_xava_005fid_005f3.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f3.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(188,14) name = name type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fid_005f3.setName(idCollection);
        int _jspx_eval_xava_005fid_005f3 = _jspx_th_xava_005fid_005f3.doStartTag();
        if (_jspx_th_xava_005fid_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f3);
        _jspx_th_xava_005fid_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f3, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f3_reused);
      }
      out.write("_col");
      out.print(columnIndex);
      out.write("\" style=\"overflow: hidden; ");
      out.print(width);
      out.write('"');
      out.write(' ');
      out.print(lastRowEvent);
      out.write(">\n");
      out.write("\t\t<nobr> \n");
      out.write("\t\t");
 if (!subview.isCollectionMembersEditables()) {
      out.write("\n");
      out.write("\t\t\t");
 if (referenceName == null) { 
      out.write("\n");
      out.write("\t\t\t\t");
      out.print(fvalue);
      out.write("&nbsp;\n");
      out.write("\t\t\t");
 } else { 
      out.write("\n");
      out.write("\t\t\t\t");
      //  xava:descriptionsList
      org.openxava.web.taglib.DescriptionsListTag _jspx_th_xava_005fdescriptionsList_005f0 = (org.openxava.web.taglib.DescriptionsListTag) _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005freadOnlyAsLabel_005fnobody.get(org.openxava.web.taglib.DescriptionsListTag.class);
      boolean _jspx_th_xava_005fdescriptionsList_005f0_reused = false;
      try {
        _jspx_th_xava_005fdescriptionsList_005f0.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fdescriptionsList_005f0.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(194,4) name = reference type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fdescriptionsList_005f0.setReference(referenceName);
        // /xava/editors/elementCollectionEditor.jsp(194,4) name = readOnlyAsLabel type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fdescriptionsList_005f0.setReadOnlyAsLabel(true);
        int _jspx_eval_xava_005fdescriptionsList_005f0 = _jspx_th_xava_005fdescriptionsList_005f0.doStartTag();
        if (_jspx_th_xava_005fdescriptionsList_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005freadOnlyAsLabel_005fnobody.reuse(_jspx_th_xava_005fdescriptionsList_005f0);
        _jspx_th_xava_005fdescriptionsList_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fdescriptionsList_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005fdescriptionsList_005f0_reused);
      }
      out.write("\t\n");
      out.write("\t\t\t");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
 } else if (referenceName != null) { 
      out.write('\n');
      out.write('	');
      out.write('	');
      //  xava:descriptionsList
      org.openxava.web.taglib.DescriptionsListTag _jspx_th_xava_005fdescriptionsList_005f1 = (org.openxava.web.taglib.DescriptionsListTag) _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005fnobody.get(org.openxava.web.taglib.DescriptionsListTag.class);
      boolean _jspx_th_xava_005fdescriptionsList_005f1_reused = false;
      try {
        _jspx_th_xava_005fdescriptionsList_005f1.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fdescriptionsList_005f1.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(197,2) name = reference type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fdescriptionsList_005f1.setReference(referenceName);
        int _jspx_eval_xava_005fdescriptionsList_005f1 = _jspx_th_xava_005fdescriptionsList_005f1.doStartTag();
        if (_jspx_th_xava_005fdescriptionsList_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fdescriptionsList_0026_005freference_005fnobody.reuse(_jspx_th_xava_005fdescriptionsList_005f1);
        _jspx_th_xava_005fdescriptionsList_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fdescriptionsList_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005fdescriptionsList_005f1_reused);
      }
      out.write('\n');
      out.write('	');
      out.write('	');
 } else { 
      out.write("\n");
      out.write("\t\t<span id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f4 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      boolean _jspx_th_xava_005fid_005f4_reused = false;
      try {
        _jspx_th_xava_005fid_005f4.setPageContext(_jspx_page_context);
        _jspx_th_xava_005fid_005f4.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(199,12) name = name type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005fid_005f4.setName("editor_" + view.getPropertyPrefix() + propertyName);
        int _jspx_eval_xava_005fid_005f4 = _jspx_th_xava_005fid_005f4.doStartTag();
        if (_jspx_th_xava_005fid_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f4);
        _jspx_th_xava_005fid_005f4_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f4, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f4_reused);
      }
      out.write("\">\n");
      out.write("\t\t");
      //  xava:editor
      org.openxava.web.taglib.EditorTag _jspx_th_xava_005feditor_005f0 = (org.openxava.web.taglib.EditorTag) _005fjspx_005ftagPool_005fxava_005feditor_0026_005fthrowPropertyChanged_005fproperty_005fnobody.get(org.openxava.web.taglib.EditorTag.class);
      boolean _jspx_th_xava_005feditor_005f0_reused = false;
      try {
        _jspx_th_xava_005feditor_005f0.setPageContext(_jspx_page_context);
        _jspx_th_xava_005feditor_005f0.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(200,2) name = property type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005feditor_005f0.setProperty(propertyName);
        // /xava/editors/elementCollectionEditor.jsp(200,2) name = throwPropertyChanged type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005feditor_005f0.setThrowPropertyChanged(throwPropertyChanged);
        int _jspx_eval_xava_005feditor_005f0 = _jspx_th_xava_005feditor_005f0.doStartTag();
        if (_jspx_th_xava_005feditor_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005feditor_0026_005fthrowPropertyChanged_005fproperty_005fnobody.reuse(_jspx_th_xava_005feditor_005f0);
        _jspx_th_xava_005feditor_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005feditor_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005feditor_005f0_reused);
      }
      out.write("\n");
      out.write("\t\t</span>\n");
      out.write("\t\t");
 } 
      out.write("\t\n");
      out.write("\t \t</nobr>  \n");
      out.write("\t\t</div>\n");
      out.write("\t</td>\t\t\n");
      out.write("\t");
 if (searchAction != null && subview.isLastSearchKey(p.getName())) {	
      out.write("\n");
      out.write("\t<td class=\"");
      out.print(cssCellClass);
      out.write("\" style=\"");
      out.print(cellStyle);
      out.write("; padding-left: 3px; padding-right: 0px;\">\n");
      out.write("\t\t");
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f1 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      boolean _jspx_th_xava_005faction_005f1_reused = false;
      try {
        _jspx_th_xava_005faction_005f1.setPageContext(_jspx_page_context);
        _jspx_th_xava_005faction_005f1.setParent(null);
        // /xava/editors/elementCollectionEditor.jsp(208,2) name = action type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005faction_005f1.setAction(searchAction);
        // /xava/editors/elementCollectionEditor.jsp(208,2) name = argv type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_xava_005faction_005f1.setArgv("keyProperty="+propertyName);
        int _jspx_eval_xava_005faction_005f1 = _jspx_th_xava_005faction_005f1.doStartTag();
        if (_jspx_th_xava_005faction_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f1);
        _jspx_th_xava_005faction_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005faction_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005faction_005f1_reused);
      }
      out.write(" \t\t\t\t\t\t\t\t\n");
      out.write("\t</td>\n");
      out.write("\t");
 } 
      out.write('\n');

	}
}

      out.write("\n");
      out.write("</tr>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "collectionTotals.jsp", out, false);
      out.write('\n');
 if (sortable) { 
      out.write("</tbody>");
 } 
      out.write("\n");
      out.write("</table>\n");
 if (resizeColumns && scrollSupported) { 
      out.write("\n");
      out.write("</div>\n");
 } 
      out.write("\n");
      out.write("</div> \n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_xava_005fid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f0 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    boolean _jspx_th_xava_005fid_005f0_reused = false;
    try {
      _jspx_th_xava_005fid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f0.setParent(null);
      // /xava/editors/elementCollectionEditor.jsp(45,12) name = name type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_xava_005fid_005f0.setName("collection_scroll");
      int _jspx_eval_xava_005fid_005f0 = _jspx_th_xava_005fid_005f0.doStartTag();
      if (_jspx_th_xava_005fid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f0);
      _jspx_th_xava_005fid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fid_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005fid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:message
    org.openxava.web.taglib.MessageTag _jspx_th_xava_005fmessage_005f0 = (org.openxava.web.taglib.MessageTag) _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody.get(org.openxava.web.taglib.MessageTag.class);
    boolean _jspx_th_xava_005fmessage_005f0_reused = false;
    try {
      _jspx_th_xava_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fmessage_005f0.setParent(null);
      // /xava/editors/elementCollectionEditor.jsp(138,12) name = key type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_xava_005fmessage_005f0.setKey("remove_row");
      int _jspx_eval_xava_005fmessage_005f0 = _jspx_th_xava_005fmessage_005f0.doStartTag();
      if (_jspx_th_xava_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_xava_005fmessage_005f0);
      _jspx_th_xava_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_xava_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_xava_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:message
    org.openxava.web.taglib.MessageTag _jspx_th_xava_005fmessage_005f1 = (org.openxava.web.taglib.MessageTag) _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody.get(org.openxava.web.taglib.MessageTag.class);
    boolean _jspx_th_xava_005fmessage_005f1_reused = false;
    try {
      _jspx_th_xava_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fmessage_005f1.setParent(null);
      // /xava/editors/elementCollectionEditor.jsp(144,12) name = key type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_xava_005fmessage_005f1.setKey("remove_row");
      int _jspx_eval_xava_005fmessage_005f1 = _jspx_th_xava_005fmessage_005f1.doStartTag();
      if (_jspx_th_xava_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fxava_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_xava_005fmessage_005f1);
      _jspx_th_xava_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_xava_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_xava_005fmessage_005f1_reused);
    }
    return false;
  }
}
